name: Guardrail CI Pipeline

on:
  pull_request:
    branches:
      - main
      - master

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  terraform-checks:
    name: IaC Linting and Security
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'

      - name: Checkout Code
        uses: actions/checkout@v7

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v6
        with:
          tflint_version: latest

      - name: Run TFLint
        run: tflint --init && tflint

      - name: Run Checkov Scan
        uses: bridgecrewio/checkov-action@master
        with:
          directory: .
          framework: terraform
          # soft_fail: false ensures the pipeline breaks if misconfigurations are found
          soft_fail: false 

  container-security:
    name: Docker Build and Scan
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'

      - name: Checkout Code
        uses: actions/checkout@v7

      - name: Build Sample Docker Image
        run: |
          docker build -t python-microservice:${{ github.sha }} .

      - name: Run Trivy Vulnerability Scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'python-microservice:${{ github.sha }}'
          format: 'table'
          # exit-code: '1' is the "Fail Safe" that blocks the PR
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
